# Change these first
owner: DigintLab # Your GitHub organization or username, where this repository lives
repo: infra-status # The name of this repository

delay: 5000 # 5 seconds

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/20 * * * *"
  
sites:
  - name: Company Website
    url: https://doubleextortion.com
  - name: Platform Frontend
    url: https://app.doubleextortion.com
  - name: Platform Authentication Endpoint (prod)
    url: auth.eu-ep1.doubleextortion.com
  - name: Platform Primary API Endpoint (prod)
    url: https://api.eu-ep1.doubleextortion.com/v1/
  - name: Platform Secondary API Endpoint (prod)
    url: https://api.eu-ep1b.doubleextortion.com/v1/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.digintlab.com
  # baseUrl: /your-repo-name
  logoUrl: https://doubleextortion.com/wp-content/uploads/logo-deplatform.png
  name: DEP Infrastructure Status
  introTitle: "Double Extortion platform infrastructure status monitoring"
  introMessage: Status page tracking DE platform availability.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://digintlab.com/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
