# Change these first
owner: DigintLab # Your GitHub organization or username, where this repository lives
repo: infra-status # The name of this repository

delay: 5000 # 5 seconds

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/20 * * * *"

sites:
  - name: Company Website
    url: https://doubleextortion.com
    slug: company-website
  - name: Platform Frontend
    url: https://app.doubleextortion.com
    slug: app-prod-fronted
  - name: Platform Authentication Endpoint (prod)
    url: https://auth.eu-ep1.doubleextortion.com
    slug: app-prod-auth
  - name: Platform Primary API Endpoint (prod)
    url: https://api.eu-ep1.doubleextortion.com/v1/
    slug: app-prod-api-eu-primary
    expectedStatusCodes:
      - 403
    __dangerous__body_down_if_text_missing: '"Missing Authentication Token"'
  - name: Platform Secondary API Endpoint (prod)
    url: https://api.eu-ep1b.doubleextortion.com/v1/
    slug: app-prod-api-eu-secondary
    expectedStatusCodes:
      - 403
    __dangerous__body_down_if_text_missing: '"Missing Authentication Token"'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.digintlab.com
  # baseUrl: /your-repo-name
  logoUrl: https://doubleextortion.com/wp-content/uploads/logo-deplatform.png
  name: DEP Infrastructure Status
  introTitle: "Double Extortion platform infrastructure status monitoring"
  introMessage: Status page tracking DE platform availability.
  themeUrl: https://status.digintlab.com/theme.css
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://digintlab.com/
  js: |
    window.addEventListener("load", () => {
      const kill = () => {
        // 1) Remove incident sections by heading text
        document.querySelectorAll("section").forEach((s) => {
          const h = s.querySelector("h2,h3");
          const t = (h?.textContent || "").toLowerCase();
          if (t.includes("active incidents") || t.includes("past incidents")) s.remove();
        });

        // 2) Hide any nav links/tabs that include "Incidents"
        document.querySelectorAll("a,button").forEach((el) => {
          const t = (el.textContent || "").toLowerCase();
          if (t.includes("incidents")) el.style.display = "none";
        });

        // 3) Remove the Upptime footer branding
        document.querySelectorAll("footer").forEach((f) => {
          const t = (f.textContent || "").toLowerCase();
          if (t.includes("upptime") || t.includes("powered by")) f.remove();
        });
      };

      kill();
      setInterval(kill, 1000); // keep it hidden after re-renders
    });

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
